// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: Copyright (c) 2026 Spiral Pool Contributors

package coin

import (
	"encoding/hex"
	"testing"
)

// TestQBXSymbol verifies basic coin metadata.
func TestQBXSymbol(t *testing.T) {
	c := NewQBXCoin()

	if c.Symbol() != "QBX" {
		t.Errorf("expected symbol QBX, got %s", c.Symbol())
	}

	if c.Name() != "Q-BitX" {
		t.Errorf("expected name Q-BitX, got %s", c.Name())
	}
}

// TestQBXAlgorithm verifies QBX uses SHA-256d and has no SegWit.
func TestQBXAlgorithm(t *testing.T) {
	c := NewQBXCoin()

	if c.Algorithm() != "sha256d" {
		t.Errorf("expected algorithm sha256d, got %s", c.Algorithm())
	}

	if c.SupportsSegWit() {
		t.Error("QBX must NOT support SegWit")
	}
}

// TestQBXNetworkParams verifies port and block time constants.
func TestQBXNetworkParams(t *testing.T) {
	c := NewQBXCoin()

	if c.DefaultRPCPort() != 8344 {
		t.Errorf("expected RPC port 8344, got %d", c.DefaultRPCPort())
	}

	if c.DefaultP2PPort() != 8345 {
		t.Errorf("expected P2P port 8345, got %d", c.DefaultP2PPort())
	}

	if c.BlockTime() != 150 {
		t.Errorf("expected block time 150s, got %d", c.BlockTime())
	}

	if c.CoinbaseMaturity() != 100 {
		t.Errorf("expected coinbase maturity 100, got %d", c.CoinbaseMaturity())
	}
}

// TestQBXVersionBytes verifies QBX uses Dilithium-derived version bytes,
// NOT Bitcoin's 0x00/0x05.
func TestQBXVersionBytes(t *testing.T) {
	c := NewQBXCoin()

	// QBX P2PKH = 0x32 (M...), NOT Bitcoin's 0x00 (1...)
	if c.P2PKHVersionByte() != 0x32 {
		t.Errorf("expected P2PKH version 0x32, got 0x%02x — QBX uses M... not 1... addresses", c.P2PKHVersionByte())
	}

	// QBX P2SH = 0x37 (P...), NOT Bitcoin's 0x05 (3...)
	if c.P2SHVersionByte() != 0x37 {
		t.Errorf("expected P2SH version 0x37, got 0x%02x — QBX uses P... not 3... addresses", c.P2SHVersionByte())
	}
}

// TestQBXAddressValidation verifies address decoding for all QBX address types.
func TestQBXAddressValidation(t *testing.T) {
	c := NewQBXCoin()

	tests := []struct {
		name     string
		address  string
		valid    bool
		addrType AddressType
	}{
		// Valid P2PKH — starts with M (version byte 0x32)
		{
			name:     "valid P2PKH M-address (pool address)",
			address:  "MQr2QunAiMQTg4s84cEpm2GSRiRUt4Vn5y",
			valid:    true,
			addrType: AddressTypeP2PKH,
		},
		// Valid P2PKH — from getnewaddress "" pq on real QBX node
		{
			name:     "valid P2PKH M-address (generated by node)",
			address:  "MFSqtVn3HMKZDzdSADTJjqmVNgStP5GKdR",
			valid:    true,
			addrType: AddressTypeP2PKH,
		},
		// pq-prefix addresses cannot be decoded by stratum
		{
			name:    "pq address rejected (cannot decode for coinbase)",
			address: "pqSomePostQuantumAddress123456789abc",
			valid:   false,
		},
		// Bitcoin P2PKH (1...) must NOT be accepted
		{
			name:    "bitcoin 1-address rejected",
			address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
			valid:   false,
		},
		// Bitcoin P2SH (3...) must NOT be accepted
		{
			name:    "bitcoin 3-address rejected",
			address: "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
			valid:   false,
		},
		// SegWit bc1q must NOT be accepted
		{
			name:    "segwit bc1q address rejected",
			address: "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq",
			valid:   false,
		},
		// Empty address
		{
			name:    "empty address",
			address: "",
			valid:   false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := c.ValidateAddress(tt.address)
			if tt.valid && err != nil {
				t.Errorf("expected valid address, got error: %v", err)
			}
			if !tt.valid && err == nil {
				t.Errorf("expected invalid address to be rejected, but it was accepted")
			}

			if tt.valid {
				_, addrType, decErr := c.DecodeAddress(tt.address)
				if decErr != nil {
					t.Errorf("DecodeAddress failed for valid address: %v", decErr)
				}
				if addrType != tt.addrType {
					t.Errorf("expected address type %v, got %v", tt.addrType, addrType)
				}
			}
		})
	}
}

// TestQBXCoinbaseScriptDilithiumOpcode is the CRITICAL test for the bad-cb-pq fix.
//
// QBX consensus rule (validation.cpp CheckBlock):
//
//	Every coinbase vout[0] MUST use IsPQPayToPubKeyHash() —
//	OP_DUP OP_HASH160 <20b> OP_EQUALVERIFY OP_CHECKSIGDILITHIUM (0xC4).
//
// A standard P2PKH script ending with OP_CHECKSIG (0xAC) causes the
// QBX node to return "bad-cb-pq" and reject the block.
func TestQBXCoinbaseScriptDilithiumOpcode(t *testing.T) {
	c := NewQBXCoin()

	params := CoinbaseParams{
		PoolAddress: "MQr2QunAiMQTg4s84cEpm2GSRiRUt4Vn5y",
	}

	script, err := c.BuildCoinbaseScript(params)
	if err != nil {
		t.Fatalf("BuildCoinbaseScript failed: %v", err)
	}

	// Dilithium P2PKH script must be exactly 25 bytes
	if len(script) != 25 {
		t.Errorf("expected 25-byte Dilithium P2PKH script, got %d bytes", len(script))
	}

	// Byte 0: OP_DUP
	if script[0] != 0x76 {
		t.Errorf("script[0]: expected OP_DUP (0x76), got 0x%02x", script[0])
	}

	// Byte 1: OP_HASH160
	if script[1] != 0xa9 {
		t.Errorf("script[1]: expected OP_HASH160 (0xa9), got 0x%02x", script[1])
	}

	// Byte 2: PUSH 20 bytes
	if script[2] != 0x14 {
		t.Errorf("script[2]: expected PUSH_20 (0x14), got 0x%02x", script[2])
	}

	// Bytes 3-22: 20-byte pubkey hash (from M... address decoding)
	hash := script[3:23]
	if len(hash) != 20 {
		t.Errorf("expected 20-byte hash in script, got %d", len(hash))
	}

	// Byte 23: OP_EQUALVERIFY
	if script[23] != 0x88 {
		t.Errorf("script[23]: expected OP_EQUALVERIFY (0x88), got 0x%02x", script[23])
	}

	// Byte 24: MUST be OP_CHECKSIGDILITHIUM (0xC4), NOT OP_CHECKSIG (0xAC)
	// This is the fix for "bad-cb-pq" — QBX rejects blocks where coinbase
	// vout[0] uses standard OP_CHECKSIG instead of Dilithium variant.
	if script[24] == 0xac {
		t.Fatalf("REGRESSION: script ends with OP_CHECKSIG (0xac) — "+
			"QBX node will reject block with 'bad-cb-pq'. "+
			"Must use OP_CHECKSIGDILITHIUM (0xc4). "+
			"Full script: %s", hex.EncodeToString(script))
	}
	if script[24] != 0xc4 {
		t.Errorf("script[24]: expected OP_CHECKSIGDILITHIUM (0xc4), got 0x%02x — "+
			"QBX requires Dilithium opcode for coinbase vout[0]", script[24])
	}

	t.Logf("Coinbase script OK: %s", hex.EncodeToString(script))
	t.Logf("Final opcode: 0x%02x (OP_CHECKSIGDILITHIUM)", script[24])
}

// TestQBXCoinbaseScriptSecondAddress tests that a different valid M... address also
// produces a Dilithium P2PKH script (not address-specific).
func TestQBXCoinbaseScriptSecondAddress(t *testing.T) {
	c := NewQBXCoin()

	params := CoinbaseParams{
		PoolAddress: "MFSqtVn3HMKZDzdSADTJjqmVNgStP5GKdR",
	}

	script, err := c.BuildCoinbaseScript(params)
	if err != nil {
		t.Fatalf("BuildCoinbaseScript failed: %v", err)
	}

	if len(script) != 25 {
		t.Errorf("expected 25-byte script, got %d", len(script))
	}

	// Final opcode must always be OP_CHECKSIGDILITHIUM for any P2PKH QBX address
	if script[24] != 0xc4 {
		t.Errorf("expected OP_CHECKSIGDILITHIUM (0xc4) for any P2PKH address, got 0x%02x", script[24])
	}
}

// TestQBXCoinbaseScriptPQAddressRejected verifies that pq... addresses cannot
// be used to build a coinbase script (we cannot decode the hash from them).
func TestQBXCoinbaseScriptPQAddressRejected(t *testing.T) {
	c := NewQBXCoin()

	params := CoinbaseParams{
		PoolAddress: "pqSomePostQuantumAddress123456789abc",
	}

	_, err := c.BuildCoinbaseScript(params)
	if err == nil {
		t.Error("expected pq address to be rejected for coinbase building (cannot decode hash)")
	}
}

// TestQBXCoinbaseScriptBitcoinAddressRejected verifies Bitcoin 1.../3.../bc1q...
// addresses are rejected — QBX uses different version bytes (0x32/0x37).
func TestQBXCoinbaseScriptBitcoinAddressRejected(t *testing.T) {
	c := NewQBXCoin()

	bitcoinAddresses := []string{
		"1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2", // Bitcoin P2PKH
		"3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy", // Bitcoin P2SH
		"bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq", // Bitcoin bech32
	}

	for _, addr := range bitcoinAddresses {
		_, err := c.BuildCoinbaseScript(CoinbaseParams{PoolAddress: addr})
		if err == nil {
			t.Errorf("expected Bitcoin address %q to be rejected for QBX coinbase", addr)
		}
	}
}

// TestQBXBlockHeader verifies the 80-byte block header serialization and SHA-256d hashing.
func TestQBXBlockHeader(t *testing.T) {
	c := NewQBXCoin()

	header := &BlockHeader{
		Version:           0x20000000,
		PreviousBlockHash: make([]byte, 32),
		MerkleRoot:        make([]byte, 32),
		Timestamp:         1700000000,
		Bits:              0x1d00ffff,
		Nonce:             12345,
	}

	for i := 0; i < 32; i++ {
		header.PreviousBlockHash[i] = byte(i)
		header.MerkleRoot[i] = byte(31 - i)
	}

	serialized := c.SerializeBlockHeader(header)
	if len(serialized) != 80 {
		t.Errorf("expected 80-byte header, got %d", len(serialized))
	}

	hash1 := c.HashBlockHeader(serialized)
	hash2 := c.HashBlockHeader(serialized)

	if len(hash1) != 32 {
		t.Errorf("expected 32-byte hash, got %d", len(hash1))
	}
	if hex.EncodeToString(hash1) != hex.EncodeToString(hash2) {
		t.Error("expected deterministic hash output")
	}
}

// TestQBXDifficulty verifies diff-1 target calculation.
func TestQBXDifficulty(t *testing.T) {
	c := NewQBXCoin()

	target := c.TargetFromBits(0x1d00ffff) // Bitcoin/QBX diff-1 target
	if target.Sign() == 0 {
		t.Error("expected non-zero target for bits 0x1d00ffff")
	}

	diff := c.DifficultyFromTarget(target)
	if diff < 0.99 || diff > 1.01 {
		t.Errorf("expected difficulty ~1.0, got %.6f", diff)
	}
}

// TestQBXGenesisBlock verifies genesis block hash validation.
func TestQBXGenesisBlock(t *testing.T) {
	c := NewQBXCoin()

	expected := "407cdbc2ca102bd9e69069f25cebc2ef363a427166edba7580b41031b68549d9"

	if err := c.VerifyGenesisBlock(expected); err != nil {
		t.Errorf("expected valid genesis hash to pass: %v", err)
	}

	if err := c.VerifyGenesisBlock("0000000000000000000000000000000000000000000000000000000000000000"); err == nil {
		t.Error("expected wrong genesis hash to fail")
	}
}

// TestQBXRegistry verifies QBX and QBITX aliases are registered.
func TestQBXRegistry(t *testing.T) {
	if !IsRegistered("QBX") {
		t.Error("expected QBX to be registered")
	}
	if !IsRegistered("QBITX") {
		t.Error("expected QBITX alias to be registered")
	}

	qbx, err := Create("QBX")
	if err != nil {
		t.Fatalf("Create(QBX) failed: %v", err)
	}
	if qbx.Symbol() != "QBX" {
		t.Errorf("expected QBX symbol, got %s", qbx.Symbol())
	}

	qbitx, err := Create("QBITX")
	if err != nil {
		t.Fatalf("Create(QBITX) failed: %v", err)
	}
	if qbitx.Symbol() != "QBX" {
		t.Errorf("expected QBX symbol from QBITX alias, got %s", qbitx.Symbol())
	}
}

// TestQBXGBTRules verifies QBX requests legacy-only block templates.
// Passing ["segwit"] causes the QBX daemon to return SegWit transactions,
// which results in "unexpected-witness" block rejection.
func TestQBXGBTRules(t *testing.T) {
	c := NewQBXCoin()
	rules := c.GBTRules()
	if len(rules) != 0 {
		t.Errorf("QBX GBTRules must return empty slice (no segwit), got %v", rules)
	}
}

// TestQBXShareDiffMultiplier verifies the share difficulty multiplier.
func TestQBXShareDiffMultiplier(t *testing.T) {
	c := NewQBXCoin()
	if c.ShareDifficultyMultiplier() != 1.0 {
		t.Errorf("expected share diff multiplier 1.0, got %.2f", c.ShareDifficultyMultiplier())
	}
}

// TestQBXV030ActivationHeights verifies the v0.3.0 hard fork constants are correct.
// These must match the values in src/consensus/params.h (nLWMAHeight, nPQSigopsHeight, nPQWitnessHeight).
func TestQBXV030ActivationHeights(t *testing.T) {
	if QBXLWMAActivationHeight != 200_001 {
		t.Errorf("LWMA activation height: expected 200001, got %d", QBXLWMAActivationHeight)
	}
	if QBXPQSigopsActivationHeight != 230_000 {
		t.Errorf("PQ sigops activation height: expected 230000, got %d", QBXPQSigopsActivationHeight)
	}
	if QBXPQWitnessActivationHeight != 230_000 {
		t.Errorf("PQ witness activation height: expected 230000, got %d", QBXPQWitnessActivationHeight)
	}
	if QBXPQWitnessScaleFactor != 16 {
		t.Errorf("PQ witness scale factor: expected 16, got %d", QBXPQWitnessScaleFactor)
	}
	if QBXLWMAWindow != 18 {
		t.Errorf("LWMA window: expected 18, got %d", QBXLWMAWindow)
	}
}

// TestQBXNoStandardSegWit verifies that standard SegWit is still disabled post-v0.3.0.
// v0.3.0 introduces PQ witness (Dilithium) which is NOT standard SegWit.
func TestQBXNoStandardSegWit(t *testing.T) {
	c := NewQBXCoin()
	if c.SupportsSegWit() {
		t.Error("QBX must NOT report standard SegWit support — PQ witness is a separate spend path")
	}
	rules := c.GBTRules()
	for _, r := range rules {
		if r == "segwit" {
			t.Error("GBTRules must not include 'segwit' — would cause unexpected-witness block rejection")
		}
	}
}
